package com.github.t1.wunderbar.junit.provider;

import com.github.t1.wunderbar.http.HttpInteraction;
import com.github.t1.wunderbar.http.HttpRequest;
import com.github.t1.wunderbar.http.HttpResponse;

import java.lang.annotation.Retention;

import static java.lang.annotation.RetentionPolicy.RUNTIME;

/// You can use this annotation on a method to, e.g., clean up the data of a single interaction.
///
/// If there are several methods annotated as [AfterInteraction], their execution order is not defined;
/// but you can use the [Order][org.junit.jupiter.api.Order] annotation to specify the order explicitly.
///
/// The annotated method can optionally take parameters of these types:
/// - [HttpInteraction]: expected interaction,
/// - [HttpRequest]: expected request,
/// - [HttpResponse]: expected response,
/// - [WunderBarExecution][com.github.t1.wunderbar.junit.provider.WunderBarExecution]: meta data about the running interaction.
///
/// The annotated method can optionally return an object of one of these types to change the expectations or actual response,
/// e.g. to replace an id actually generated by the database:
/// - [HttpResponse]: expected response.
///
/// See also: [AfterDynamicTest]
@Retention(RUNTIME)
public @interface AfterInteraction {}
