apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wunderbar
  annotations:
    github.com/project-slug: t1/wunderbar
  links:
  - title: GitHub Actions
    url: https://github.com/t1/wunderbar/actions
    icon: dashboard
spec:
  type: other
  lifecycle: unknown
  owner: t1
