package com.github.t1.wunderbar.junit.consumer;

import static java.util.Locale.ROOT;

/// The mode to run a test annotated as [WunderBarApiConsumer].
/// The default is [AUTO], so the level is determined by the test name.
public enum Level {
    /// Automatically determine the level from the test name:
    /// - If the name ends with `ST`, it's a [SYSTEM] test,
    /// - if the name ends with `IT`, it's an [INTEGRATION] test,
    /// - otherwise it's a [UNIT] test.
    ///
    /// This is the default.
    AUTO,

    /// Use Mockito to stub the expectation. The fastest turn-around.
    ///
    /// This is generally done in a test class ending with `Test`.
    UNIT,

    /// Start an http service locally and save all requests and responses in a contract file,
    /// by default a `bar` file and optionally an OpenAPI JSON file.
    /// This tests the actual annotations on your API interface as well as the de/serialization.
    /// And it specifies the API you expect a service to provide, even before that service exists.
    ///
    /// This is generally done in a test class ending with `IT`.
    INTEGRATION,

    /// Call a pre-installed `wunderbar-mock-server`.
    /// How you deploy it and how you configure your service to call the mock-server is out of the scope of WunderBar.
    ///
    /// Use [Service.endpoint] to configure where the mock-service or real service runs.
    ///
    /// You _can_ use this also to explore the behavior of a real service, but it won't understand the calls
    /// that are generated by `given` calls.
    ///
    /// This level is chosen automatically if a test class ends with `ST`.
    SYSTEM;

    @Override public String toString() {return name().toLowerCase(ROOT);}
}
