package com.github.t1.wunderbar.junit.consumer;

import com.github.t1.wunderbar.junit.WunderBarException;

import java.lang.reflect.AnnotatedElement;
import java.lang.reflect.AnnotatedParameterizedType;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.util.Arrays;
import java.util.Optional;
import java.util.stream.Stream;

/// Convenience [SomeData] class to generate values of a single type automatically derived from
/// the generic type parameter `T`.
/// You just need to override the [some][SomeData.some] method.
///
/// A common use-case is that you want your generator to work only for some tags in `@Some`.
/// To do so, you can simply annotate the type parameter like this:
/// ```
/// class CustomId extends SomeSingleTypes<@Some("id") String> {
///     public String some(Some some, Type type, AnnotatedElement location) {
///         return "custom-id";
///     }
/// }
/// ```
///
/// This also works for generic types, e.g. a type `CustomGeneric<?>` can be generated by a
/// `class CustomGenericGenerator extends SomeSingleTypes<CustomGeneric<?>>>`.
/// You can then safely cast the `Type` parameter in your `some` method,
/// e.g. `var nestedType = ((ParameterizedType) type).getActualTypeArguments()[0];`
@SuppressWarnings("unchecked")
public abstract class SomeSingleTypes<T> implements SomeData {
    protected final Class<T> type;
    protected final Some some;

    public SomeSingleTypes() {
        var typeOfT = ((ParameterizedType) this.getClass().getGenericSuperclass()).getActualTypeArguments()[0];
        this.type = (Class<T>) ((typeOfT instanceof ParameterizedType) ? rawType(typeOfT) : typeOfT);
        this.some = ((AnnotatedParameterizedType) this.getClass().getAnnotatedSuperclass())
                .getAnnotatedActualTypeArguments()[0].getAnnotation(Some.class);
    }

    @Override public Optional<T> some(Some some, Type type, AnnotatedElement location) {
        var maybeRawType = (type instanceof ParameterizedType) ? rawType(type) : type;
        if (this.type.equals(maybeRawType) && matches(some)) {
            var value = generate(some, type, location);
            if (value == null) throw new WunderBarException(
                    "[" + this + "] generated a null value" + ((location == null) ? "" : " for " + location));
            return Optional.of(value);
        } else return Optional.empty();
    }

    private boolean matches(Some some) {
        if (this.some == null) return true;
        if (some == null) return this.some.value().length == 0;
        var actual = Arrays.asList(some.value());
        return Stream.of(this.some.value()).allMatch(actual::contains);
    }

    private static Type rawType(Type type) {return ((ParameterizedType) type).getRawType();}

    public abstract T generate(Some some, Type type, AnnotatedElement location);
}
