package com.github.t1.wunderbar.junit.consumer;

import javax.enterprise.util.AnnotationLiteral;
import java.lang.annotation.Retention;

import static java.lang.annotation.RetentionPolicy.RUNTIME;

/**
 * Generate random data to be used for a {@link org.junit.jupiter.api.extension.ParameterResolver parameter or field}.
 * The basic set of value types are generated by the {@link SomeBasics}; and you can {@link com.github.t1.wunderbar.junit.Register register}
 * your own {@link SomeData generators}.
 */
@Retention(RUNTIME)
public @interface Some {
    /** A list of "tags" passed to {@link SomeData custom generators} for fine-control, e.g. <code>invalid</code>. */
    String[] value() default {};

    Some LITERAL = new SomeLiteral();

    final class SomeLiteral extends AnnotationLiteral<Some> implements Some {
        @Override public String[] value() {return new String[0];}
    }
}
