mp:
  graphql:
    showErrorMessage:
      "com.github.t1.wunderbar.demo.product.Products$BusinessException"
quarkus:
  log:
    min-level: DEBUG
    category:
      "com.github.t1":
        level: DEBUG
