name: Java CI

on: [push]

jobs:
  build-full:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: { java-version: 11 }
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
    - run: mvn --batch-mode --show-version --no-transfer-progress install
