name: Qodana Code Scanning
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
  schedule:
  - cron: '17 13 * * 2'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Qodana Scan'
      uses: JetBrains/qodana-action@v4.2.1
      with:
        linter: jetbrains/qodana-jvm
