# inspired by https://blog.codecentric.de/en/2021/02/github-actions-pipeline/
name: Release

on:
  milestone:
    types: [ closed ]

jobs:
  maven-release:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Will start a Maven Central upload for milestone ${{ github.event.milestone.title }}"

    - uses: actions/checkout@v2

    - name: Set up Maven Central Repository
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}

    - name: Prepare release to Maven Central
      run: |
        git config user.email "snackbox@sintr.eu"
        git config user.name "GitHub-Release-Action"
        mvn --batch-mode --no-transfer-progress release:prepare

    - name: Perform release to Maven Central
      run: mvn --batch-mode --no-transfer-progress release:perform
      env:
        MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

    - name: Push updated poms
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  github-release:
    needs: [ maven-release ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v3
      id: get-latest-tag
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        result-encoding: string
        script: |
          const query = `query ($owner: String!, $name: String!) {
            repository(owner: $owner, name: $name) {
             refs(refPrefix: "refs/tags/", first: 1, orderBy: {field: TAG_COMMIT_DATE, direction: DESC}) {
               edges { node { name } }
             }
            }
          }`;
          const variables = {
            owner: context.repo.owner,
            name: context.repo.repo
          }
          const result = await github.graphql(query, variables)
          const tag = result.repository.refs.edges[0].node.name
          console.log(tag)
          return tag.substr(1)

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get-latest-tag.outputs.result }}
        release_name: v${{ steps.get-latest-tag.outputs.result }}
        body: |
          Download it from [Maven Central](https://repo1.maven.org/maven2/com/github/t1/wunderbar.junit/${{ steps.get-latest-tag.outputs.result }}/wunderbar.junit-${{ steps.get-latest-tag.outputs.result }}.jar) or add a dependency to your `pom.xml`:

          ```xml
          <dependency>
              <groupId>com.github.t1</groupId>
              <artifactId>wunderbar</artifactId>
              <version>${{ steps.get-latest-tag.outputs.result }}</version>
          </dependency>
          ```

          [*Release Notes for Milestone ${{ github.event.milestone.title }}*](${{ github.event.milestone.html_url }}?closed=1)
          ${{ github.event.milestone.description }}
        draft: false
        prerelease: false
